<?php

declare(strict_types=1);

namespace Ipsocode\Auditing\Tests\Feature\Database;

use Hypervel\Contracts\Foundation\Application;
use Hypervel\Support\Facades\Config;
use Hypervel\Support\Facades\DB;
use Hypervel\Support\Facades\Schema;
use Ipsocode\Auditing\Support\AuditTables;
use Ipsocode\Auditing\Tests\TestCase;
use Workbench\App\Models\Article;

class AuditSchemaTest extends TestCase
{
    private const AUDITS_MIGRATION = '2026_06_06_000001_create_audits_table.php';

    private const AUDIT_DETAILS_MIGRATION = '2026_06_06_000002_create_audit_details_table.php';

    protected function defineEnvironment(Application $app): void
    {
        parent::defineEnvironment($app);

        // Never connected to — pretend() renders the DDL without executing it.
        $app->get('config')->set('database.connections.mysql_pretend', [
            'driver' => 'mysql',
            'host' => '127.0.0.1',
            'port' => 3306,
            'database' => 'nowhere',
            'username' => 'nobody',
            'password' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
        ]);
    }

    /**
     * The DDL the given migration would issue on MySQL. SQLite maps `char` to a
     * bare `varchar` with no length, so it cannot catch a column too narrow for
     * the value the driver writes.
     *
     * @return array<int, string>
     */
    private function mysqlDdl(string $migration): array
    {
        $definition = require dirname(__DIR__, 3) . '/database/migrations/' . $migration;

        Config::set('auditing.connection', 'mysql_pretend');

        return array_map(
            static fn (array $entry): string => $entry['query'],
            DB::connection('mysql_pretend')->pretend(static fn () => $definition->up())
        );
    }

    private function createTableStatement(string $migration): string
    {
        foreach ($this->mysqlDdl($migration) as $query) {
            if (str_starts_with($query, 'create table')) {
                return $query;
            }
        }

        $this->fail("no create table statement generated by [{$migration}]");
    }

    public function testTheEventColumnCanHoldAWholeEventName(): void
    {
        // The event name is written verbatim ("restored", "attach", or a manual
        // audit's own name); a char(1) column cannot hold it.
        $ddl = $this->createTableStatement(self::AUDITS_MIGRATION);

        $this->assertStringContainsString('`event` varchar(255) not null', $ddl);
        $this->assertStringNotContainsString('`event` char(1)', $ddl);
    }

    public function testTheAuditsTableDdlMatchesWhatTheDriverWrites(): void
    {
        $ddl = $this->createTableStatement(self::AUDITS_MIGRATION);

        $this->assertStringContainsString('`user_agent` varchar(1023) null', $ddl);
        $this->assertStringContainsString('`ip_address` varchar(45) null', $ddl);
        $this->assertStringContainsString('`url` text null', $ddl);
        $this->assertStringContainsString('`auditable_type` varchar(255) not null', $ddl);
    }

    public function testTheBatchColumnIsNullableAndIndexed(): void
    {
        // Nullable because most audits are written outside a batch, and indexed
        // because fetching a batch back by id is the only reason it exists.
        $ddl = implode("\n", $this->mysqlDdl(self::AUDITS_MIGRATION));

        $this->assertStringContainsString('`batch_uuid` char(36) null', $ddl);
        $this->assertStringContainsString('`audits_batch_uuid_index`(`batch_uuid`)', $ddl);
    }

    public function testTheDetailsTableIsLinkedByACascadingForeignKey(): void
    {
        $ddl = implode("\n", $this->mysqlDdl(self::AUDIT_DETAILS_MIGRATION));

        $this->assertStringContainsString('`audit_id` bigint unsigned not null', $ddl);
        $this->assertStringContainsString('references `audits` (`id`) on delete cascade', $ddl);
    }

    public function testEveryRecordedEventNameSurvivesARoundTrip(): void
    {
        $article = Article::factory()->create();
        $article->update(['title' => 'V2']);
        $article->delete();
        $article->restore();

        $this->assertSame(
            ['created', 'updated', 'deleted', 'restored'],
            $article->audits()->orderBy('id')->pluck('event')->all()
        );
    }

    public function testBothAuditTablesAreCreated(): void
    {
        $this->assertTrue(Schema::hasTable(AuditTables::audits()));
        $this->assertTrue(Schema::hasTable(AuditTables::auditDetails()));
    }

    public function testTheAuditsTableCarriesEveryColumnTheDriverWrites(): void
    {
        $expected = [
            'id', 'user_type', 'user_id', 'event', 'auditable_type', 'auditable_id',
            'url', 'ip_address', 'user_agent', 'tags', 'batch_uuid', 'created_at', 'updated_at',
        ];

        foreach ($expected as $column) {
            $this->assertTrue(
                Schema::hasColumn(AuditTables::audits(), $column),
                "audits.{$column} is missing"
            );
        }
    }

    public function testDetailRowsAreStampedWithACreatedAtOnly(): void
    {
        $this->assertTrue(Schema::hasColumn(AuditTables::auditDetails(), 'created_at'));
        $this->assertFalse(Schema::hasColumn(AuditTables::auditDetails(), 'updated_at'));

        $article = Article::factory()->create();

        $this->assertNotNull($article->audits()->sole()->details->first()->created_at);
    }

    public function testDeletingAnAuditCascadesToItsDetails(): void
    {
        $article = Article::factory()->create();

        $audit = $article->audits()->sole();
        $auditId = $audit->getKey();

        $this->assertGreaterThan(0, $audit->details()->count());

        $audit->delete();

        $this->assertSame(
            0,
            DB::table(AuditTables::auditDetails())->where('audit_id', $auditId)->count()
        );
    }
}
